### ISSUE TITLE
Document about configuration file

### ISSUE THREAD

**Issue by JokerQyou** [nodemailer/wildduck-webmail#18]
As I play around with a local installed version of the webmail frontend, I noticed there is no way to get rid of the error detail. E.g., I tried to login as a user that does no exist, the login page showed me this:
![image](https://user-images.githubusercontent.com/1465267/57571305-df9e5200-743e-11e9-82ed-f790ea63a3fa.png)
But if I try that in the official demo site, it only shows the red flash message "Authentication error". So I must be missing some logging configuration.

I know the file `default.toml` contains all the configuration key, but I find it very confusing. For example, there's this section:

```toml
[www]
    host=false
    port=3000
    proxy=false
    postsize="5MB"
    log="dev"
    secret="a cat"
    secure=false
    listSize=20
```

What does `host` mean? How does `secure` affect the listening port? What should I fill in `log`?
I would very much appreciate some documentation around it, for example as some comment in the code, or as a wiki page of this repository.

Thank you for this wonderful product, and have a nice day.
