### ISSUE TITLE
Hide configuration info for disabled protocol

### ISSUE THREAD

**Issue by JokerQyou** [nodemailer/wildduck-webmail#19]
The webmail uses a standalone configuration file ([default.toml][webmail-default-config]), there is this section which controls the configuration info shown in `/help` page:

```toml
[setup]
    # these values are shown in the configuration help page
    [setup.imap]
        hostname="localhost"
        secure=true
        port=9993
    [setup.pop3]
        hostname="localhost"
        secure=true
        port=9995
    [setup.smtp]
        hostname="localhost"
        secure=false
        port=2587
```

But if POP3 is disabled, the webmail would not know, and still displays those info in `/help` page.

I would like to suggest adding a `disabled` key to the `[setup.*]` section, and hide the corresponding info:

```toml
    [setup.pop3]
        disabled=true
```

[webmail-default-config]: https://github.com/nodemailer/wildduck-webmail/blob/master/config/default.toml
